### ISSUE TITLE
Email Signup: Hook up MailChimp feed

### ISSUE THREAD

**Issue by adamwalter** [VitalDevTeam/Center-for-Medical-Simulation#319]

**Comment by lmajerus** [comment]
Hi @mavedisian, I'm receiving email notifications with new email sign-ups to our mailing list (and their interests from the check boxes) from Form ID 3. I think I was looking at Form ID 1 when I asked you how the fields were mapped because in Form ID 3, it's really obvious :)

2 issues (probably neither are technical problems):
1) Not all the new subscribers are added to our Mailchimp list 
Since some Form ID 3 folks are getting through to the MailChimp list, should I assume that the reason not everyone is in Mailchimp is that they haven't completed the double opt-in confirmation?

Example: newest addition was Sema Kuguoglu (skuguoglu@gmail.com) that came in June 15, 2017 at 2:09AM. I searched Mailchimp for the name (separately first/last) and email and that person is not on our list.
![image](https://user-images.githubusercontent.com/22547623/27192700-4bc4469a-51ca-11e7-8637-fe2983f0284b.png)

Example: first addition was Federico Salvetti (networking@logosnet.org) where he seems to be signed up but there's this weird "pending confirmation" message in MailChimp.
![2017-06-15 13_07_31-view member _networking logosnet org_ _ mailchimp](https://user-images.githubusercontent.com/22547623/27193353-7f92ab0e-51cc-11e7-8a9b-d9f4d117f278.png)

2) There's drop off from Form ID 1 to Form ID 3: meaning people are not completing Form 3 to actually get on the list - can't get on the list from Form 1 and that's all they've completed.). Is this normal behavior? How can we improve completion of Form ID 3? I'm wondering if we have to state that you are not yet signed up until you complete Form ID 3 (obviously, I wouldn't state "Form ID 3"). Thoughts?

**Comment by mavedisian** [comment]
1.) You are absolutely correct. This link may help in further understanding the process: http://kb.mailchimp.com/lists/signup-forms/understanding-the-double-opt-in-process

2.) The only improvement I can think of is combining the 2 forms into a single form and including that in the footer to avoid the 2 (3?!) step process, however A. Space is limited and B. there are all kinds of optional fields on form #3 that you'd be missing out on...
