### ISSUE TITLE
Course Application - Notification emails not sent at all

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#327]
Looking at the Entries for the Course application, we have not received any of those after we went live May 8. These earlier ones that I did on May 4 did come through by email. 
![applynow-entries](https://cloud.githubusercontent.com/assets/22547623/25860613/0a30c82a-34b0-11e7-822f-ade84f954d04.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, I understand.. let me investigate.

**Comment by mavedisian** [comment]
Hello @lmajerus, after some length of testing and tweaking, I have confirmed all the notifications are working as expected re: the Course Application form. To account for any discrepancies between the hidden field and what Gravity Forms is displaying the field as (there may be characters being rendered differently than how we see it on the front end, such as spaces, symbols, or other), I've changed the conditional logic for each notification to use "Contains" instead of "Is". To set these up in the future, just use "Contains" and match a unique string within the course name to successfully make it trigger. 

For example, the notification's conditional logic for Participant: DASH/Gateway Form is submitted will look for ANY match inside "Selected Course" to either "Debriefing" and/or "Gateway". 

Please test and follow up with your results, hopefully we can close this issue!

**Comment by lmajerus** [comment]
Hi @mavedisian, ok so the good news is that some of your test messages came through. The bad news - not all of them and I didn't receive an email for a real application that was submitted this morning.

Here's what came through from your tests yesterday:
- ACRMF6/MOCA June 22, 2017
- OR Teams July 19-21, 2017 (both applications at 11:09 and 11:11)
- L&D1 Aug 2, 2017 (both applications at 11:12 and 11:19)

No emails for the L&DCRM-6  on Aug 9, both Comprehensives Aug 14-17, and both Gateway Aug 24 tests. Also no email for today's real application for Gateway Aug 24 entered at 9:56am June 15.

Here's a screenshot of my email inbox:
![email-notification-test-june-14-2017](https://user-images.githubusercontent.com/22547623/27192081-03598ee4-51c8-11e7-9bf1-8e2f90e04a82.png)

Here's a screenshot of entries as of this comment time:
![entries-applications-june-14-2017](https://user-images.githubusercontent.com/22547623/27192099-0e26268e-51c8-11e7-8c3e-edb0080b3221.png)

Idea: what if I remove the conditional if/than logic and have a separate notification to match each course type? Should I try this in staging?

**Comment by twwheeler** [comment]
@mavedisian before we change the rules, we should check the SendGrid logs to confirm whether the messages in questoin were actually triggered and not delivered, (or filtered) or if there's a logic issue with the notification conditional.

**Comment by lmajerus** [comment]
Hi @mavedisian. Finally good news!!! All the Admin and Participant Notification emails are now working. It was some missing conditional logic in the Notification message. Using the "Selected Course" field and "contains" rather than "is" seems to work!

Yesterday I submitted test applications for each available course in the drop-down list (all but DASH). The participant notifications went out for all except the Advanced Instructor Course but when I looked into it, the notification Conditional Logic didn't have the Advanced course in the list. I added it and retested - voila, the participant notification for Advanced Course went through as expected. The Admin notifications were hit or miss: only MOCA, L&DCRM-1, and OR Teams admin notifications went through.

I looked at all the Notifications this morning and updated the conditional logic. When I submitted new test applications for each course type, both Admin and Participant notifications went through as expected.

I think this issue is finally resolved so I'm closing the ticket.
