### ISSUE TITLE
Google Webmaster Tools Error Message: Increase in “soft-404” pages on https://harvardmedsim.org/

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#344]
We've received an email from Google Webmaster Tools that we've had an increase in soft 404 errors on our site. Here's the link to the Crawl Errors directly in Webmaster Tools: 
https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=https://harvardmedsim.org/

Below and attached is the email we received from Google:
Message type: [WNC-655200]
Search Console
Increase in “soft-404” pages on https://harvardmedsim.org/

To: Webmaster of https://harvardmedsim.org/,

Googlebot identified a significant increase in the number of URLs on https://harvardmedsim.org/  that should return a 404 (not found) error, but currently don't. This can cause a bad experience for your users, who might have been looking for a specific page, but end up elsewhere on your website. This misconfiguration can also prevent Google from showing the correct page in search results.

Recommended Actions:

1

Identify the URLs with errors
Open the Crawl Errors report in your Search Console account to review the list of sample URLs.
Check Crawl Errors
2

Fix the issue
Check your server and CMS settings to make sure that these URLs return a 404 (Not Found) or 410 (Gone) HTTP response code in response to requests for non-existent pages. You may need help from your server administrator or hoster for this step.
3

Verify the fix
Once you've fixed the URLs with errors, make sure that Googlebot can access and see your content properly, or that they return a proper error result code. You can verify this using Fetch as Google.
Fetch as Google
Need more help?

•
See the Crawl Errors - Soft 404 Help Center article.
•
Ask questions in our forum for more help - mention message type [WNC-655200].

[email-Increase-soft-404-google.pdf](https://github.com/VitalDevTeam/Center-for-Medical-Simulation/files/1014293/email-Increase-soft-404-google.pdf)

**Comment by mavedisian** [comment]
@lmajerus I did a pass at resolving Soft 404's... I resolved over 100 instances of real soft 404's however there are a majority associated with the plugin used for the new course calendar. When an event passes, the event page still lives on the site, but displays info that the course is no longer available (past date). Because Google's automated analysis determines these to be soft 404's even though we are displaying content that lets the user know the event no longer exists, there's nothing we can do about these instances except safely ignore them.
