### ISSUE TITLE
Calendar: No publicly (or privately) published events showing

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#378]
I'm not sure when this started but someone pointed out today that our website calendar is empty 
[CalendarWebPage.pdf](https://github.com/VitalDevTeam/Center-for-Medical-Simulation/files/1321378/CalendarWebPage.pdf). I went into the back end and all events are there (both publicly published, draft, and privately published events are still there. Miraculously, the upcoming courses are correctly listed in the Apply-now page and the Upcoming Course Dates table on Course pages.

What changed to make it so the events disappeared from display on the calendar?

**Comment by lmajerus** [comment]
All of a sudden, the publicly & privately published events now appear. Did you do something to resolve the issue? I'm at a loss as to what happened to make the calendar display blank for at least 12 hours and now works within a few minutes of reporting the issue. Any ideas?

**Comment by JuliaAhumada** [comment]
We are looking into this.

**Comment by mavedisian** [comment]
Good morning Laura, I'm also not sure what the issue was. I pushed up a new update to the Advanced Tiny MCE plugin before doing any testing, and that's when I noticed there was no issue. It doesn't make sense if that was the cause, bit I'm not sure how the issue started so perhaps it was! Can you confirm it looks fine now?

**Comment by lmajerus** [comment]
Yes, the calendar now shows events correctly. I'm not sure when it started. Someone emailed me at 10pm last night saying it was blank. When I first checked this morning, it was still blank. I looked at the back-end events worried that they all disappeared but they were still there. I couldn't figure out what might have happened (I haven't done any custom CSS or anything other than Add new event/page/resource/blog post/etc). So I added this ticket. 

After creating the ticket, I sent a message to our staff so I wouldn't be bombarded with colleagues all telling me that the calendar was down. Less than a minute after sending out that email, I received a reply that the events all appeared on the calendar again. I checked and sure enough, all the events appeared. 

I'm stumped as to what could have happened. I agree with you, the Tiny MCE shouldn't have had any impact. Maybe the site updates need to be implemented? I haven't ever touched updates. There are 3 available, including the Event Calendar. Should the Event Calendar be updated?
![image](https://user-images.githubusercontent.com/22547623/30705041-613c223c-9ec2-11e7-98e8-153c16bc1ab4.png)

**Comment by mavedisian** [comment]
CMS is on our service and maintenance retainer, as such we handle plugin updates and testing on the 15th of every month. It would be better for us to handle the updates since we track code changes and keeping the code repository consistent across testing and production is a good idea. 

On Friday, CMS received plugin updates for: 

- ACF Pro
- Gravity Forms
- Events Calendar
- Migrate DB Pro

**Comment by lmajerus** [comment]
Hmm, well if the update was done on the 15th, the last update couldn't have been the issue. I'll continue to abstain from doing any updates on the site.
